-- ================================================================
-- WMdb 智能云平台 - Oracle / OceanBase-Oracle 全量表结构
-- 适用引擎：Oracle 12c / 18c / 19c / 21c / OceanBase Oracle Mode
-- ================================================================

-- 1. 系统角色定义表
CREATE TABLE sys_role (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR2(50) NOT NULL,
  role_code VARCHAR2(50) NOT NULL,
  role_name VARCHAR2(100) NOT NULL,
  description VARCHAR2(255),
  CONSTRAINT uk_ora_role UNIQUE (tenant_id, role_code)
);

-- 2. 系统用户实名与鉴权表
CREATE TABLE sys_user (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR2(50) NOT NULL,
  username VARCHAR2(100) NOT NULL,
  phone VARCHAR2(50),
  real_name VARCHAR2(100),
  id_card VARCHAR2(50),
  email VARCHAR2(100),
  resource_group VARCHAR2(255),
  password_cipher VARCHAR2(255),
  password_hash VARCHAR2(255),
  role VARCHAR2(100) DEFAULT 'DEV',
  wechat VARCHAR2(100),
  work_wechat VARCHAR2(100),
  dingtalk VARCHAR2(100),
  feishu VARCHAR2(100),
  status NUMBER(5) DEFAULT 1,
  avatar_url VARCHAR2(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_ora_user UNIQUE (tenant_id, username)
);

-- 3. 业务资源组与审批责任人映射表
CREATE TABLE resource_group (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR2(50) NOT NULL,
  group_name VARCHAR2(100) NOT NULL,
  dept_name VARCHAR2(100),
  dev_lead VARCHAR2(100),
  dba_lead VARCHAR2(100),
  description VARCHAR2(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_ora_group UNIQUE (tenant_id, group_name)
);

-- 4. 数据库纳管多数据源实例配置表
CREATE TABLE db_instance (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR2(50) NOT NULL,
  name VARCHAR2(100),
  db_type VARCHAR2(50),
  jdbc_url VARCHAR2(500),
  read_only_jdbc_url VARCHAR2(500),
  username VARCHAR2(100),
  password_cipher VARCHAR2(255),
  env VARCHAR2(20),
  status VARCHAR2(20) DEFAULT 'APPROVED',
  CONSTRAINT uk_ora_inst UNIQUE (tenant_id, name)
);

-- 5. SQL 变更审批工单主表
CREATE TABLE sql_ticket (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR2(50) NOT NULL,
  instance_id NUMBER(19) NOT NULL,
  type VARCHAR2(20) NOT NULL,
  reason VARCHAR2(255),
  sql_text CLOB,
  file_url VARCHAR2(255),
  status VARCHAR2(20) NOT NULL,
  submitter_id NUMBER(19),
  submitter_id_card VARCHAR2(50),
  submit_time TIMESTAMP,
  process_instance_id VARCHAR2(64),
  db_name VARCHAR2(100),
  applicant_name VARCHAR2(100),
  applicant_id_card VARCHAR2(50),
  workflow_template_id NUMBER(19),
  workflow_template_name VARCHAR2(100),
  execution_mode VARCHAR2(50) DEFAULT 'IMMEDIATE',
  scheduled_time TIMESTAMP,
  batch_size NUMBER(10),
  interval_ms NUMBER(10),
  affect_rows_estimate NUMBER(10),
  actual_affect_rows NUMBER(10),
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. SQL 变更工单详情表
CREATE TABLE sql_ticket_detail (
  id NUMBER(19) NOT NULL PRIMARY KEY,
  tenant_id VARCHAR2(50) NOT NULL,
  ticket_id NUMBER(19) NOT NULL,
  sql_text CLOB,
  attachment_oss_key VARCHAR2(255),
  affect_rows_estimate NUMBER(10),
  actual_affect_rows NUMBER(10)
);

-- 7. 工单操作流水审计表
CREATE TABLE ticket_operation_log (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id NUMBER(19) NOT NULL,
  operator_id_card VARCHAR2(50),
  operator_name VARCHAR2(100),
  operation_type VARCHAR2(50),
  node_name VARCHAR2(100),
  comment CLOB,
  tenant_id VARCHAR2(50) NOT NULL,
  created_time VARCHAR2(50)
);

-- 8. SQL 执行审计与回滚日志表
CREATE TABLE sql_audit_log (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR2(50) NOT NULL,
  ticket_id NUMBER(19),
  execute_sql CLOB,
  cost_time_ms NUMBER(19),
  status VARCHAR2(20),
  error_trace CLOB,
  previous_hash VARCHAR2(255),
  current_hash VARCHAR2(255),
  rollback_sql CLOB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 9. 数据库查询审计日志表
CREATE TABLE query_audit_log (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR2(50) NOT NULL,
  instance_id NUMBER(19),
  db_name VARCHAR2(100),
  query_sql CLOB,
  cost_time_ms NUMBER(19),
  affect_rows NUMBER(19),
  operator_name VARCHAR2(100),
  created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 10. 动态脱敏规则表
CREATE TABLE data_masking_rule (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR2(50) NOT NULL,
  rule_name VARCHAR2(100),
  column_pattern VARCHAR2(100),
  algorithm VARCHAR2(50),
  params VARCHAR2(255),
  status NUMBER(5) DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 11. 动态审批流模板配置表
CREATE TABLE workflow_template (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR2(50) NOT NULL,
  template_name VARCHAR2(100) NOT NULL,
  flow_type VARCHAR2(50),
  resource_groups CLOB,
  target_databases CLOB,
  node_config CLOB,
  condition_expression VARCHAR2(255),
  is_pinned NUMBER(5) DEFAULT 0,
  description VARCHAR2(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
