spring:
  application:
    name: wmdb-backend

wmdb:
  jwt:
    secret: "A_VERY_LONG_SECRET_KEY_FOR_WMDB_V2_COMMERCIAL_EDITION_2024_06_24_AND_MOVED_TO_YML!"
    expiration: 86400000
  minio:
    endpoint: "http://localhost:9000"
    access-key: "minioadmin"
    secret-key: "minioadmin"
    bucket: "wmdb-attachments"
